binance:
  api_key: "TU_API_KEY"
  api_secret: "TU_API_SECRET"

telegram:
  token: "TU_TOKEN_TELEGRAM"
  chat_id: "TU_CHAT_ID"

trading:
  initial_capital: 1000
  risk_per_trade: 0.02
  daily_loss_limit: 0.05
  pairs:
    - "BTCUSDT"
    - "ETHUSDT"
    - "BNBUSDT"
