binance:
  api_key: "NAlz27WWFABMVJsGtQ3AgFSVff7NwwRFl3qZQqfC1659i3bh18gN7wdwkrV93fBD"
  api_secret: "RQHZrCocr8FrENmCMFj7PdNAyxGPdNT1XXQD19oc4KOIAdLEQ12bl4EL01uMuMgW"

telegram:
  token: "TU_TOKEN_DE_TELEGRAM"
  chat_id: "TU_CHAT_ID"

trading:
  initial_capital: 100
  risk_per_trade: 0.015
  daily_loss_limit: 0.05
  pairs:
    - "BTCUSDT"
    - "ETHUSDT"
    - "BNBUSDT"

exchange:
  api_key: "YOUR_EXCHANGE_API_KEY"
  api_secret: "YOUR_EXCHANGE_API_SECRET"
