# DEV
binance:
  api_key: "x3wKNyqoht1rwJKHwgpt7LjzagiqqvI2JR7geibtyK28cG9Vjj5UOhnKYBGpizRX"
  api_secret: "6s7jHCJYcZ33m2nxagFSjRkDCN5QkK7MFe8VKixVO3ouDuAuOamfRJhfCgR2pluX"

# PRODUCTION
# binance:
#   api_key: "NAlz27WWFABMVJsGtQ3AgFSVff7NwwRFl3qZQqfC1659i3bh18gN7wdwkrV93fBD"
#   api_secret: "RQHZrCocr8FrENmCMFj7PdNAyxGPdNT1XXQD19oc4KOIAdLEQ12bl4EL01uMuMgW"

telegram:
  token: "7833148217:AAGLH2-RAkd1RMo2dYWwGH2WBBr9EyZ96vI"
  chat_id: "6800921"

trading:
  initial_capital: 1000
  risk_per_trade: 0.02
  daily_loss_limit: 0.05
  pairs:
    - "BTCUSDT"
    - "ETHUSDT"
    - "BNBUSDT"
